config/routes.rb
Datalog::Application.routes.draw do

  resources :posts

  get "landing/index"
  resources :ads do
    collection do
      get 'myads'
      get 'contact'
    end
  end

 devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :events
  resources :landings

  root 'landings#index'

end

app/models/landing.rb
class Landing < ActiveRecord::Base
	validates :email, :presence => "true"
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  	@landing = Landing.new
  end

  def new
	@landing = Landing.new
  end

  def create
  	@landing = Landing.new(params[:landing].permit(:email))
  	if @landing.save
    	redirect_to root_path
    	flash[:notice] = "Thanks for signing up! We'll get back to you soon!"
  	else
    	redirect_to root_path
  	end
  end

  def destroy
  	@landing = Landing.all
  	@landing.destroy
  end

  private
  def landing_params
    params.require(:landing).permit(:email)
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landings/_form.html.erb
<%= form_for :landing do |f| %>
	<%= f.email :email, :placeholder => "Please enter your email" %>
	<%= f.submit %>
<% end %>

app/views/landings/index.html.erb
<style type="text/css">
.header {
	display: none!important;
}
</style>

<div class="blue_half">
	<div class="inner_container">
		<div class="float_left">
		<div class="logo_land">
			<h1><span class="lighter">Ad</span>Lookr</h1>
		</div>
		<h1 class="head_shadow">Amazing classified ads.
		<br>Get noticed. Get AdLookr.</h1>
		<h2>Launching soon, sign up to get notified.</h2>
		<div class="beta_apply">
			<%= form_for :landing, url: landings_path do |f| %>
				<%= f.email_field :email, :placeholder => "Enter your email", :class => "beta_email" %>
				<%= f.submit "Sign Up"%>
			<% end %>
			<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>
		</div>
	</div>
	<div class="float_right">
		<%= image_tag 'screenshot.jpg' %>
	</div>
</div>
</div>
<div class="main_info">
	<div class="inner_container">

		<div class="header_area">
			<div class="first25">
				<h2>An amazing way to make an ad </h2>
				
				<p>We are an amazing classified ads site.</br>
				We help your ad get noticed.
				</p>
			</div>
		</div>

		<center><a href="https://twitter.com/adlookr" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @adlookr</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></center>

		<div class="how_works">
			<h2>How it works</h2>
					
			<div>

				<div class="afixdspace_grid_f center_as">
    				<div class="pic_sec_f">
      					<%= image_tag "example.jpg", :alt => "It seems you have adblocked, to view this ad please disable it." %>
    				</div>
    				<div class="text_info_f">
    					<div class="text_title">
      					<span class="bold title">Example Ad</span></br>
    					</div>
    				<div class="extra_info_f">
        				<p>This is a short description...</p>
        				<span class="bold">Belfast</span></br>
        				<span class="bold">www.adlookr.com</span>
      				</div>
					</div>

  				</div> 
  				<div class="desc-fix">
  					<p>
  						With AdLookr all you need to do</br>
  						is create your free account and then</br>
  						start making your ad.</br></br>
  						All the ads on AdLookr have a sleek</br>
  						and smooth design, making it easier</br>
  						for you to display your information</br>
  						clearly and precisely.</br></br>
  						Hover over the title on the ad above.</br>
  						(If your on a mobile device there's no need to hover.)</br>
  						See? Plenty of room for more information.</br>
  					</p>
  					<h2>What can I advertise?</h2>

  					<p>
  						You can advertise anything!</br>
  						Here at AdLookr we make it easier</br>
  						to create an ad.</br>
  						No problems. No fuss,</br> 
  						just enter your ad's details.</br>
  						Whether you're selling </br>
  						a car, a television or a games console</br>
  						you're guaranteed a quality service.
  					</p>
  				</div>

			</div>
		</div>

		<div class="secure_pay">
			<h2>So what's the catch?</h2>
					
			<p>
				There isn't any!</br>
				With our ads being FREE,</br>
				there's nothing that you can't do!
			</p>
		</div>

		</div>
				<div class="blue_second">
					<h2>We're nearly ready to launch, </br>sign up and we'll let you know when we launch</h2>
					<div class="beta_apply">
			<%= form_for :landing, url: landings_path do |f| %>
				<%= f.email_field :email, :placeholder => "Enter your email", :class => "beta_email" %>
				<%= f.submit "Sign Up"%>
			<% end %>
			<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>
		</div>

	</div>
</div>

app/views/landings/new.html.erb
<style type="text/css">
.header {
	display: none!important;
}
</style>

<%= form_for :landing, url: landings_path do |f| %>
	<%= f.text_field :email, :placeholder => "Please enter your email" %>
	<%= f.submit "Apply"%>
<% end %>