config/routes.rb
Datalog::Application.routes.draw do

  resources :posts

  get "landing/index"
  resources :ads do
    collection do
      get 'myads'
      get 'contact'
    end
  end

 devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :events
  resources :landings

  root 'landings#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html itemscope itemtype="http://schema.org/Organization">
<html>
<head>
  <title>AdLookr | Classified Ads - Get Noticed, Get AdLookr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= tag :meta, :name => "description", :content => "The #1 classified ad site. Launching soon, sign up to get notified." %>
  <link rel="author" href="https://plus.google.com/u/1/100402716539715687271"/>
  <%= tag :meta, :name => "og:title", :content => "AdLookr - The #1 Ad Site" %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">  
  <%= tag :meta, :name => "og:description", :content => "The #1 site for posting an ad and looking for that one thing you've always wanted, whether it's a car or a small bike for the kids , we've got you covered." %>
  <!-- Add the following three tags inside head. -->
<meta itemprop="name" content="AdLookr - Finding what you want, when you want.">
<meta itemprop="description" content="With AdLookr you can post and ad, or look for anything, whether it&#39;s a new car or a small bike for the kids, we&#39;ve got it.">
<meta itemprop="image" content="https://lh3.googleusercontent.com/-3e55sfgQZlU/UtasoOvqIrI/AAAAAAAAABI/ciWa67sFcs8/s400-no/ADLOOKR.jpg">

  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
  <script src="http://cdn.jotfor.ms/js/stripe.js?v=3.1.1257" type="text/javascript"></script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40691709-3', 'adlookr.com');
  ga('send', 'pageview');

</script>

<script type="text/javascript">
$(function(){
    $('#pull').mouseenter(function(){
        $('#dropdown').parent().addClass('altbg')
    }).mouseout(function(){
        $(this).parent().removeClass('altbg')
    });
});
</script>
</head>
<body>
 
<div id="container">
<div class="header">
  <div class="header_fix">
  <div class="logo">
    <a href="http://www.adlookr.com"><span class="lighter">Ad</span>Lookr</a>
  </div>
	<div class="navs">
    <%= form_tag ads_path, :method => :get do %>
  <p class="search_f">
    <%= text_field_tag :search, params[:search], :class => "glow_f" %>
    <%= submit_tag "Search", :name => nil, :class => "submit" %>
<% end %>
		<%= link_to "Home", ads_path + "?utf8=✓&search=Search+Here...", :class => "ads_link" %>
		<% if user_signed_in? %>
      <%= link_to 'New Ad', new_ad_path %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'My Ads', myads_ads_path %>
    <% end %>
    
		<% if user_signed_in? %>
			<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
		<% else %>
			<%= link_to "Sign In / Sign Up", new_user_session_path %>
		<% end %>
    <a href="mailto:adlookr@gmail.com?Subject=Hi%20AdLookr" target="_top">Contact</a>

	</div>
</div>
</div>




<%= yield %>

</body>
</html>